/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class info_freelibrary_openjpeg_JP2Bridge */

#ifndef _Included_info_freelibrary_openjpeg_JP2Bridge
#define _Included_info_freelibrary_openjpeg_JP2Bridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     info_freelibrary_openjpeg_JP2Bridge
 * Method:    decode
 * Signature: (Linfo/freelibrary/openjpeg/JP2Decoding;)V
 */
JNIEXPORT void JNICALL Java_info_freelibrary_openjpeg_JP2Bridge_decode
  (JNIEnv *, jobject, jobject);

/*
 * Class:     info_freelibrary_openjpeg_JP2Bridge
 * Method:    encode
 * Signature: (Linfo/freelibrary/openjpeg/JP2Encoding;)V
 */
JNIEXPORT void JNICALL Java_info_freelibrary_openjpeg_JP2Bridge_encode
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
